# Generated by Django 4.2 on 2023-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
