# Generated by Django 4.2 on 2023-04-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_curriculum_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculum",
            name="age",
        ),
        migrations.AddField(
            model_name="curriculum",
            name="score",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
