# Generated by Django 4.2 on 2023-04-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_remove_curriculum_age_curriculum_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculum",
            name="score",
        ),
    ]
