# Generated by Django 4.2 on 2023-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cnt",
            field=models.IntegerField(null=True),
        ),
    ]
